# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :osx, '10.10'

target 'manage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for manage
#  pod 'SwiftyJSON', '~> 4.0'

end
